### ISSUE TITLE
마이크 쓰는 법

### ISSUE THREAD

**Issue by JECH2** [JECH2/GameDesignProject_KAIST#10]

**Comment by JECH2** [comment]
해결!
https://github.com/balatj/Guitar-Tuner

아래 코드가 Naudio라는 라이브러리 사용

**Comment by JECH2** [comment]
Naudio 라이브러리에서 audio device받고 하는 거 다 처리할 수 있도록 API 제공!

**Comment by JECH2** [comment]
Naudio 라이브러리의 WaveIn이 유니티와 호환되지 않는 것인지.. 프로그램은 돌아가는데 인풋 버퍼에 사운드 sample이 안들어가서 유니티의 Microphone을 사용하여 인풋을 받는 것을 유니티에서 처리하게 됨

**Comment by JECH2** [comment]
그러나 유니티의 마이크 인풋 레이턴시 이슈 존재함(한 0.5초~1초정도 됨)
https://github.com/keijiro/Lasp
다음 라이브러리로 줄일 순 있다는데 아쉽게도 지원하는 유니티버전이 Unity 2019.3 or later..

**Comment by JECH2** [comment]
어쨋거나 유니티 마이크 인풋 관련 참고자료
https://www.youtube.com/watch?v=GHc9RF258VA
Microphone 클래스
https://docs.unity3d.com/2018.3/Documentation/ScriptReference/Microphone.html

**Comment by Cliwo** [comment]
저희 이제 리포에 코드를 올릴때가 된것 같군요.
화요일날 코드 push에 대해서도 논의해봅시다~

**Comment by JECH2** [comment]
넵 좋습니다!

**Comment by HajunKim** [comment]
네 좋아요
