### ISSUE TITLE
Sending data from pitch detection to Unity

### ISSUE THREAD

**Issue by HajunKim** [JECH2/GameDesignProject_KAIST#14]

**Comment by JECH2** [comment]
유니티 console에 frequency 화면 띄우기

**Comment by JECH2** [comment]
유니티 싱글톤만들어서 sound manager만들기!

**Comment by JECH2** [comment]
싱글톤으로 Sound Manager 만들어서 Update() 사용해서 Pitch, Decibel 값 출력할 수 있게 함
그러나 레이턴시 이슈 존재
https://drive.google.com/file/d/1a-kY2ohd1173B4wFQPHN42fsgsA49av_/view?usp=sharing

**Comment by JECH2** [comment]
Pitch detection할 때 FFT하는 방법들이 생각보다 빨라서 써봤는데 휘파람같은 건 잘하는데 사람 목소리를 잘 못해서 기존에 쓰던 Yin 알고리즘을 쓰는 게 나을 듯
그러나 Yin 알고리즘은 정확한 대신 correlation 값 계산하는 특성 상 소리 input의 크기(데시벨)가 커야 잘 된다는 단점이 있는듯

https://support.unity3d.com/hc/en-us/articles/206485253-How-do-I-get-Unity-to-playback-a-Microphone-input-in-real-time-
https://narusegawa.tistory.com/entry/%EC%9C%A0%EB%8B%88%ED%8B%B0%EC%97%90%EC%84%9C-%EC%9D%8C%EC%84%B1Voice-Sound%EC%9D%B8%EC%8B%9D
https://answers.unity.com/questions/157940/getoutputdata-and-getspectrumdata-they-represent-t.html?childToView=158800#answer-158800
https://stackoverflow.com/questions/53030560/read-microphone-decibels-and-pitch-frequency
https://ajh322.tistory.com/171
https://m.blog.naver.com/theo5970/221585602643

**Comment by JECH2** [comment]
![image](https://user-images.githubusercontent.com/26477914/97171364-b14a3900-17d0-11eb-8bb5-d45d4caebfc7.png)
mapping value 잘 됨!

**Comment by JECH2** [comment]
FPS Sample(별이님 컴퓨터)에서 테스트했을 때 정상 작동 그러나 하준님 컴퓨터에서는 AnalyzeSound()에서 audioSource.GetOutputData(buffer, 0); 했을 때 buffer에 데이터 값이 이상하게 들어옴. 해결방법 좀 더 찾아봐야 할 듯.
(나중에 리프로듀스 티켓 만들겠습니다!)
