### ISSUE TITLE
Eunjin and Hajun decide which language to use 

### ISSUE THREAD

**Issue by HajunKim** [JECH2/GameDesignProject_KAIST#15]
Let's get it

**Comment by HajunKim** [comment]
일단 파이썬 작동 되는 것 확인했습니다. 
![Uploading 스크린샷 2020-10-07 오전 1.43.26.png…]()

**Comment by HajunKim** [comment]
내일 더 깊이 코드를 음미해보겠습니다

**Comment by JECH2** [comment]
주말 중으로 결정짓기

**Comment by HajunKim** [comment]
현재 Unity와 Python Socket 통신법에 대한 이해와 활용하기 위해 어떻게 해야하는지 전반적으로 이해를 계속 하고 있습니다. 
빠르게 완료되기를 바랬는데 시간이 상당히 걸리고 있네요. 
하나를 해결하면 또다시 생길 수 있는 문제가 하나있고 이래서 좀 오래걸렸는데 결국에는 화요일 모임전까지는 해서 가도록 하겠습니다.
