### ISSUE TITLE
레이저 만들기

### ISSUE THREAD

**Issue by Cliwo** [JECH2/GameDesignProject_KAIST#20]
[하모니언즈 게임 핵심 시스템 구현]

색깔 변경시킬 수 있게
Harmony 레이저

DUE 10/30 Fri

**Comment by Cliwo** [comment]
https://youtu.be/WXvV2GJOysg

**Comment by Cliwo** [comment]
https://youtu.be/A3caNnvT_mA 
Visual Effect Graph 로 구현하고자합니다. 
Collision도 지원하고 기존의 Node 형 구현이라 편할 것 같아요.

**Comment by Cliwo** [comment]
https://drive.google.com/file/d/17xuomBcRxz4TH2zMHblST_M9AMqow9Ow/view?usp=sharing
첫번째 영상 구현한 영상입니다.

Bloom이 안되네요. 원인 찾아보겠습니다.

**Comment by Cliwo** [comment]
중간 결과입니다
<img width="1288" alt="스크린샷 2020-10-20 오후 4 35 18" src="https://user-images.githubusercontent.com/15336467/96555117-560cd800-12f2-11eb-803b-9c3be5dc9b37.png">
<img width="1290" alt="스크린샷 2020-10-20 오후 4 35 29" src="https://user-images.githubusercontent.com/15336467/96555127-586f3200-12f2-11eb-83b9-46cd2f79ec27.png">
<img width="1291" alt="스크린샷 2020-10-20 오후 4 35 44" src="https://user-images.githubusercontent.com/15336467/96555121-573e0500-12f2-11eb-894e-10570015f2b8.png">
https://drive.google.com/file/d/1IvNXd8s6AQ39JmjgnZBL-joiD7Z-ixXo/view?usp=sharing

float 값의 변화에 따라 색이 잘 변화합니다


<img width="832" alt="ColorRange Graph" src="https://user-images.githubusercontent.com/15336467/96555202-6de45c00-12f2-11eb-9b94-46b1c09afd56.png">

**Comment by HajunKim** [comment]
done by 승찬
