### ISSUE TITLE
맵 내에 Target 만들기(세우기)

### ISSUE THREAD

**Issue by byeoli** [JECH2/GameDesignProject_KAIST#22]
[하모니언즈 게임 핵심 시스템 구현]

- collider 활용법 
- FPS Sample 코드 내 q 입력 관련 코드 확인 필요 ----> DUE 10/20 Tue 18:00
- 만드는 방법 고안하기

DUE 10/30 Fri

**Comment by Cliwo** [comment]
FPS Sample내에 Q입력 관련.. 코멘트

아래는 제가 조사하면서 대충 정리한 글입니다.

Player가 '입력'으로 작동시키는 모든 '캐릭터의 행동' 은 Ability_ 라는 단어가 포함되는 클래스로 구현됩니다.
InputSystem.cs 은 입력이 발생했을 때 UserCommand 객체에 입력을 담는 역할을 합니다.

LocalPlayer.cs, LocalPlayerControl.cs, PlayModuleCLlient.cs 세 클래스는 client단에서만 일어나는 입력 / 서버단에서 일어나는 입력 등에 대한 처리를 담당합니다.
(정확한 로직은 모르겠음)

FPS Sample의 특정 기능들은 Client side에서만 돌아갈때와 Server-Client 단에서 돌아갈 때 구현 방법이 다르므로 이것도 이러한 특징을 가질 수 있습니다.

현재 Q 입력에 매핑되어있는 Ability3는 구현은 되어있지만 사용하고있는 Ability가 없습니다. Ability의 확장가능성을 위해 열어둔 것 같습니다. (그래서 현재 Q가 음성입력을 위한 키가 되었습니다.)

<Ability를 추가하려면 어떻게 해야하는가?>
Assets/Gamedesign/Heroes/ 위치 아래에 Ability_XXX.asset 파일을 만들어주어야합니다. 
(만드는 방법이 필요하면 문의주세요!)

**Comment by byeoli** [comment]
- Target 만드는 위치 

Materials > Environment > 

> FPS Sample내에 Q입력 관련.. 코멘트
> 
> 아래는 제가 조사하면서 대충 정리한 글입니다.
> ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
> Player가 '입력'으로 작동시키는 모든 '캐릭터의 행동' 은 Ability_ 라는 단어가 포함되는 클래스로 구현됩니다.
> InputSystem.cs 은 입력이 발생했을 때 UserCommand 객체에 입력을 담는 역할을 합니다.
> 
> LocalPlayer.cs, LocalPlayerControl.cs, PlayModuleCLlient.cs 세 클래스는 client단에서만 일어나는 입력 / 서버단에서 일어나는 입력 등에 대한 처리를 담당합니다.
> (정확한 로직은 모르겠음)
> 
> FPS Sample의 특정 기능들은 Client side에서만 돌아갈때와 Server-Client 단에서 돌아갈 때 구현 방법이 다르므로 이것도 이러한 특징을 가질 수 있습니다.
> 
> 현재 Q 입력에 매핑되어있는 Ability3는 구현은 되어있지만 사용하고있는 Ability가 없습니다. Ability의 확장가능성을 위해 열어둔 것 같습니다. (그래서 현재 Q가 음성입력을 위한 키가 되었습니다.)
> 
> <Ability를 추가하려면 어떻게 해야하는가?>
> Assets/Gamedesign/Heroes/ 위치 아래에 Ability_XXX.asset 파일을 만들어주어야합니다.
> (만드는 방법이 필요하면 문의주세요!)
> ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

근데 문득

**Comment by byeoli** [comment]
**InputSystem [Asset>Scripts>Game>Systems>InputSystem]**
=> 인풋 (키보드, 마우스) 입력 모아 담는거 관련

- Q입력 
```
class InputSystem
public void AccumulateInput(ref UserCommand command, float deltaTime)

command.buttons.Or(UserCommand.Button.Ability3, Game.Input.GetKey(KeyCode.Q));
```

**Comment by byeoli** [comment]
1. Assets>Gamedesign>Heroes>Robot : Abilities 
- Abilities : Scriptable object 라는거 같음 

- [ ] Q Robot / Terraformer 에서 Terraformer는 무엇인가요? 무슨 목적으로 있는거죠? Earth-shaping? 

2. Assets>Scripts>Game>Modules>Character>Behaviours>Abilities : Ability c# 파일들 

* 1의 Abilities에 있는 GUID
- GUID : Globally Unique Identifier for the asset 
   - to identify files within projects

**Comment by byeoli** [comment]
1의 Abilities에 있는 GUID
- GUID : Globally Unique Identifier for the asset 
   - to identify files within projects

**Comment by byeoli** [comment]
아무 기능 없는 FPS 유니티 샘플에서 Scriptable object (Ability) 만드는 방법 AtoZ
[https://learn.unity.com/tutorial/create-an-ability-system-with-scriptable-objects#5cf5ecededbc2a36a1bd53b7](url)

**Comment by byeoli** [comment]
- [ ] Q 인풋이 Keycode 로 숫자로 변환되어 다뤄지고 있는 이유? 
![image](https://user-images.githubusercontent.com/42757741/96456215-2d84cf80-1259-11eb-9120-af4791e27fbb.png)
