### ISSUE TITLE
만들어진 Target 색칠하기

### ISSUE THREAD

**Issue by byeoli** [JECH2/GameDesignProject_KAIST#23]
[하모니언즈 전체 게임 핵심 시스템 구현] 

- hdrp
- 어떻게 할지 구상하기 ----> DUE 10/20 Tue 18:00
- 개발 구현 

DUE 10/30 Fri

**Comment by byeoli** [comment]
Unity Asset PaintZ 발견 ! 
- 만든이가 피드백이 굉장히 빠름 
[https://assetstore.unity.com/packages/tools/particles-effects/paintz-102269#reviews](url)

**Comment by byeoli** [comment]
Unity Asset "Paint In 3D" (유료) 
- HDRP 지원
[https://assetstore.unity.com/packages/tools/painting/paint-in-3d-26286](url)

**Comment by byeoli** [comment]
portion 
fluid animation 

찾아보기 !

**Comment by byeoli** [comment]
타겟 주위 상호작용할 수 있는 특정 거리를 잡아놓고 , 그 안에서 q 눌렀을때 activate 되게

**Comment by byeoli** [comment]
광선 검에서 collision test ! 하는 방법도 있음 ! -> ECS 기반 (승찬님) 

Unity collision test가 component 기반으로 되어 있는게 있음 
- sphere collider

**Comment by Cliwo** [comment]
liquid shader : https://assetstore.unity.com/packages/vfx/shaders/liquid-shader-173635

**Comment by Cliwo** [comment]
URP에서 물만드는 방법입니다.
HDRP에서도 적용해볼 수 있지 않을까 합니다...(?)

https://youtu.be/gRq-IdShxpU

**Comment by HajunKim** [comment]
finished - by 승찬, 별이
