### ISSUE TITLE
FPS Sample 내 MUTE 구현하기

### ISSUE THREAD

**Issue by byeoli** [JECH2/GameDesignProject_KAIST#24]
- 사운드 모듈 팀의 10/30 이후 마일스톤

**Comment by JECH2** [comment]
일단 가장 간단하게는 특정 이벤트(피격) 발생 시 -> 플레이어를 뮤트 시키고 -> 몇 초정도 지나면 플레이어 캐릭터의 뮤트를 푸는 방식으로 진행 가능할 것 같습니다!

- 유니티에서 딜레이 사용하는 방법 여러가지 중 하나 선택하기(코루틴, Invoke, 그냥 Time.deltaTime 사용하기 중)
https://sylvester127.tistory.com/2

- Mute 방법의 가능한 예시
1) Microphone.Start() Microphone.End()를 이용하여 Recording을 껐다켰다하는 방법
(https://docs.unity3d.com/ScriptReference/Microphone.html)
2) AudioSource.mute를 사용하여 Input volume = 0으로 만드는 방법
(https://docs.unity3d.com/ScriptReference/AudioSource-mute.html) 

뭔가 후자가 좋아보이는군요

**Comment by JECH2** [comment]
20201019 회의
- 코드 짜기
1. color : 12개 음을 0 ~ 1로 mapping : C -> B까지. 1/12 단위로 나눠서 맵핑
2. mute : collision 관련 이벤트 발생 시 해당 플레이어 뮤트(volume = 0), 몇 초 후 볼륨 원상복귀
- collision 관련 코드 위치 찾기
- sound 폴더 내 스크립트 공부

**Comment by JECH2** [comment]
Sound Module 내에 mute 함수로 MakePlayerMute(int timeAmount)를 만들었습니다. 
플레이어를 timeAmount 시간동안 mute 시키는 함수입니다.
mute 상태를 풀기 위해서 invoke 함수를 쓰기 위해 깔끔하진 않지만 ChangeMuteState 함수를 별도로 만들어서 사용했습니다..!

**Comment by JECH2** [comment]
https://drive.google.com/file/d/1DFx7EH57jL_K8cN8ExfBW4STNy09Wfiw/view?usp=sharing

**Comment by HajunKim** [comment]
color : 12개 음을 0 ~ 1로 mapping : C -> B까지. 1/12 단위로 나눠서 맵핑 만들었습니다. 
Dictionary 형태로. 
ex) A# 이 들어오면 해당 character에 대응되는 float value가 나온다.

**Comment by JECH2** [comment]
invoke 함수 대신 corutine 사용하기 : ? 나중에 문제 생기면 고치기

**Comment by JECH2** [comment]
피격 이벤트 위치 : FPSSample/Assets/Scripts/Game/Systems/Damage/HealthState.cs
public void ApplyDamage(ref DamageEvent damageEvent, int tick) 라는 함수에서
health -= damageEvent.damage; 라는 부분이 있는데 이부분 주석 달고 SoundModule.Instance.PlayerMute() 넣으면 되지 않을까 싶습니다.

**Comment by JECH2** [comment]
서버 연결 없이 컴퓨터 하나로 데미지 받는 상황을 어떻게 확인하지 하다가 혼자서 바닥에 총쏴도 데미지를 받을 수 있다는 하준님의 이야기를 듣고 한번 그렇게 테스트해보는 것으로 하겠습니다!
