### ISSUE TITLE
피격시, Mute가 되도록 하는 Script 찾아보기 

### ISSUE THREAD

**Issue by HajunKim** [JECH2/GameDesignProject_KAIST#28]
피격시, Mute가 되도록 하는 Script 찾아보기

**Comment by JECH2** [comment]
(실수로 다른 티켓에 코멘트 넣었습니다 ㅠㅠㅠ 여기다 다시올림)
피격 이벤트 위치 : FPSSample/Assets/Scripts/Game/Systems/Damage/HealthState.cs
public void ApplyDamage(ref DamageEvent damageEvent, int tick) 라는 함수에서
health -= damageEvent.damage; 라는 부분이 있는데 이부분 주석 달고 SoundModule.Instance.PlayerMute() 넣으면 되지 않을까 싶습니다.
