### ISSUE TITLE
피격 뮤트 테스트

### ISSUE THREAD

**Issue by JECH2** [JECH2/GameDesignProject_KAIST#31]
피격 뮤트 테스트를 부탁드립니다!

현재 git lfs 문제로 push가 반영이 안되어서 임시로 sound module 파일을 아래 리포에 업로드해두었습니다!
https://github.com/JECH2/FPS_SoundModule

< 테스트 방법 >
1. FPS sample/Assets 폴더에서 최신 sound module git clone
$ git clone https://github.com/JECH2/FPS_SoundModule.git

2.  프로젝트의 scene에 Audio Source를 추가
Game Object > Audio > Audio Source 클릭 후 object 이름을 Sound Module로 변경

3. 추가한 오브젝트를 더블 클릭 후 1.에서 다운 받은 폴더 내에 있는 SoundModule.cs script를 add component로 추가

4. SoundMixer 파일의 Microphone을 soundModule script component의 Mixer Group Microphone 변수(?)에 끌어 당겨 적용
![image.png](https://images.zenhubusercontent.com/5f69d19571535422c5e73f07/ddc3d5cc-69a0-4cf7-8148-0a0ba5996190)
![image.png](https://images.zenhubusercontent.com/5f69d19571535422c5e73f07/df488f22-d9c6-4bc6-82b7-62770c9b75c3)
(이렇게.. 마우스 위치를 보시면 될 것 같습니다!)

--> 이 상태에서 실행하시면 SoundModule의 public variable인 verbose가 체크가 되어 있어서 아아아아 하시면 Console창에서 detection 된 음정 값과 mapping value가 같이 나올 것입니다!

5. SoundModule Script의 public variable인 IsMuted를 클릭했을 때 5초간 뮤트가 되는 것을 확인해주세요. : console 창에 mute on for 5 secs.라는 메시지가 입력되고, 5초간 detection log가 발생하지 않는 것을 체크해주시면 됩니다.
![image.png](https://images.zenhubusercontent.com/5f69d19571535422c5e73f07/507c58d7-bf40-40d6-92df-14e3e2385cf6)

6. 피격 이벤트 위치 : FPSSample/Assets/Scripts/Game/Systems/Damage/HealthState.cs를 열어보시면
public void ApplyDamage(ref DamageEvent damageEvent, int tick) 라는 함수에서
health -= damageEvent.damage; 라는 부분이 있는데 이부분 주석 달고 SoundModule.Instance.PlayerMute() 를 넣어주세요.
 
7. 게임을 실행해서 땅바닥에 총을 발사해서 반사시켰을 때 플레이어가 뮤트 당하는지 확인부탁드립니다! : console 창에 mute on for 5 secs.라는 메시지가 입력되고, 5초간 detection log가 발생하지 않는 것을 체크해주시면 됩니다.

**Comment by Cliwo** [comment]
5,6,7 모두 잘 작동합니다~
얄루~~~

**Comment by JECH2** [comment]
오오오오오오오오오오~!!!!!!!! 
넘넘 좋네요!!

**Comment by HajunKim** [comment]
코드 찾느라 고생했네유 은진씨!!

**Comment by Cliwo** [comment]
https://drive.google.com/file/d/1fhl95VElk2fZ3Xo8UpL3g1Y6toJx_sIx/view?usp=sharing
