### ISSUE TITLE
Mute settings(Advanced)

### ISSUE THREAD

**Issue by JECH2** [JECH2/GameDesignProject_KAIST#32]
- 데미지가 누적되면 뮤트가 되게 하기(not 한 번)
- mute 횟수 증가시 어떻게 뮤트 시간이 달라지게 할 지!

**Comment by JECH2** [comment]
데미지가 누적되면 뮤트가 되게 하기 위해서 체력과 관련한 코드를 보고 있습니다. 기본 코드는 체력이 0이 되면, 캐릭터가 죽도록 되어 있지만, 이것을 수정하면 체력이 0이 되었을 때 뮤트가 되고, 죽음 없이 다시 체력을 초기화해주는 식으로 바꿀 수 있을 것 같습니다. 그래서 우선, 저번에 뮤트 테스트 부탁드렸던 부분 말고, 
FPSSample\Assets\Scripts\Game\Systems\Damage\HealthState.cs 코드에서 
(health <= 0) 조건문 안에 SoundModule.Instance.MakePlayerMute(5);를 넣으면 될 것 같습니다.

**Comment by JECH2** [comment]
그리고, 위의 코드가 어디서 호출되는지 확인해보니 전체 프로젝트 중FPSSample\Assets\Scripts\Game\Modules\Character\CharacterModuleServer.cs 에서만 호출하는 것을 확인했습니다.
이 코드는 모든 플레이어들(체력을 가진 엔티티)에 대해서 데미지 이벤트를 가지고 있다면 체력을 업데이트하고, healthState.ApplyDamage()를 부른 뒤, 데미지를 받은 캐릭터의 체력이 0 이하가 되면,
instigatorDamageHistory.inflictedDamage.lethal = 1;
collOwner.collisionEnabled = 0;
ragdollState.ragdollActive = 1;으로
세가지 boolean 변수를 설정합니다. 
체력이 0이 되었을 때 죽지 않게 하려면 이 변수들을 바꾸지 않도록 설정하면 되지 않을까 싶은데, 이것 외에도 캐릭터가 죽고나서 다시 리스폰 되는 상황에서의 코드도 확인해봐야 할 것 같습니다.

**Comment by JECH2** [comment]
위의 변수 중에서 lethal은,
FPSSample\Assets\Scripts\Game\Modules\Character\UI\CharacterUISystems.cs 에서
characterControl.hud.ShowHitMarker(damageHistory.inflictedDamage.lethal == 1);
으로 사용되는 것을 확인할 수 있었습니다. 근데 이상하게도 게임 안에서 검색이 안되어서 좀 알아보니 멀티 모드일 때만 이 스크립트가 재생되는 것 같습니다..

**Comment by JECH2** [comment]
그리고 collision부분은 살펴보지 않았지만, ragdollActive변수의 경우 죽고나서 래그돌 상태로 바꿔주는 곳에서만 사용되는 것 같은데, 이 부분을 잘 고치면, 플레이어 뮤트 후 래그돌 상태로 진입 -> 뮤트 풀리면서 부활(?)하도록 할 수 있을 것 같습니다.
일단 디버깅 시 멀티플레이 모드가 아니어서 플레이어가 죽고 나서 상태를 확인할 수가 없어서 ㅠㅠㅠ 일단 좀 더 확인해보겠습니다..!

**Comment by HajunKim** [comment]
확인해보았습니다 감사해요!
