### ISSUE TITLE
Collision Test

### ISSUE THREAD

**Issue by byeoli** [JECH2/GameDesignProject_KAIST#41]
1. 3D 오브젝트에다가 collision 처리, 

Debug.log 로 collision on/off 구현 (바닥 고려) collision.cs 로 구현해보기 
Target 폴더 만들고 

타겟 만들기 →  타겟에 collision 추가하기 →   on/off 뜨도록 해보기

https://victorydntmd.tistory.com/91

**Comment by JECH2** [comment]
Survival Shooter의 9.Spawning Enemies에서 Instantiate로 여러가지 스폰 포인트를 만들어두고 그 중 하나의 위치에 랜덤하게 적을 생성하는 게 있습니다! 이 코드를 수정해서 타겟 위치를 랜덤하게 생성할 수 있을 듯.

**Comment by HajunKim** [comment]
이 부분 참고해볼게요~!

**Comment by JECH2** [comment]
#43 테스트용으로 Scripts/Target/Target.cs 만들어두었고, isVitalized라는 boolean 변수를 만들어서 활성화여부를 외부 스크립트에서 확인할 수 있도록 하였습니다! 가능하다면 여기 스크립트에다가 작업 부탁드립니다!

**Comment by JECH2** [comment]
++ 작업하실 때 Scene에서 빈 오브젝트 Target 지우고 하시면 될듯합니다!
