### ISSUE TITLE
승리조건 & 엔딩 만들기

### ISSUE THREAD

**Issue by byeoli** [JECH2/GameDesignProject_KAIST#43]
승리조건 -> 엔딩

**Comment by JECH2** [comment]
Survival Shooter Game에서 GameOver Trigger를 보낼 때 GameOver! 애니메이션이 재생되어 엔딩을 만들듯이,
비슷한 방법으로 HUD Canvas의 Animator State에 WinClip, LooseClip을 추가하였고, 각각이 Win과 Loose Trigger를 이용해서 엔딩으로 접근할 수 있도록 해두었습니다. 
현재 그래서 GameOverManager.cs를 수정하여, 승리조건을 추가하였습니다.
테스트용으로 Target이라는 빈 오브젝트를 만든 후 Target.cs의 isVitalized(isActive라는 이름이 유니티에서 너무 자주쓰여서..)라는 boolean 변수가 true면, Win Trigger를 실행시켜 엔딩을 보여주도록 만들어두었습니다.
@HajunKim

**Comment by JECH2** [comment]
12.02 타겟을 3개로 만들고 승리조건에 타겟 3개가 모두 활성화되어야 게임이 끝나도록 변경함
