### ISSUE TITLE
셋 다 공통  ! 튜토리얼 끝내기 

### ISSUE THREAD

**Issue by byeoli** [JECH2/GameDesignProject_KAIST#45]
[https://learn.unity.com/tutorial/survival-shooter-training-day-phases?projectId=5c514921edbc2a002069465e&tab=overview#5c7f8528edbc2a002053b71e](url)

Survival Shooter Game Tutorial 끝내기

- [x] 하준

- [x] 은진

- [x] 별이

**Comment by JECH2** [comment]
은진 완료! 여러분, 생각보다 강의에서 사용하는 코드와 패키지로 다운받아 저희가 작업하는 코드가 많이 다릅니다..!
- Gun 날릴 때 Gun Particle이 Asset 폴더 안에 없습니다.
- 몬스터 리스폰 코드 버그 있습니다. (스폰되는 지점을 저장하는 배열의 길이 관련)
- 몬스터 죽었을 때 dead trigger 애니메이션 부분에서 지정해줘야 하는데 강의듣다보면 설명이 없습니다.
- 기본 코드에서는 score 업데이트가 두 번 일어나는데 애니메이션에서 프리팹의 Death 애니메이션에서 StartSinking()이 한 번 호출되고, EnemyHealth.cs의 Death()에서 StartSinking이 호출되기 때문입니다. 코드에서 호출되는 것을 지워주면 됩니다!
- active되어 있지 않은 오브젝트라서 nav가 실행되지 않는다는 에러가 발생하는데 이는 PausibleObject와 관련한 문제입니다. 관련한 코드를 EnemyHealth.cs에서 지우면 됩니다.

그 외에도 수동으로 맞춰줘야하는 게 있습니다..! 공부하면서 고생많으실 것 같아서 미리 에러가 발생하는 부분들을 알려드립니다.

일단 리포지토리에는 위의 버그는 다 수정해서 push했습니다!(gun particle 제외)
