### ISSUE TITLE
2명이서 할 수 있는지 테스트

### ISSUE THREAD

**Issue by JECH2** [JECH2/GameDesignProject_KAIST#46]
새벽에 그냥 자기 싫어서 하나 추가해봅니다 ㅎㅎ
예상 맵핑
- Player1P(asdw + shift1)
- Player2P(상하좌우 + shift2)
단, 이 경우 마우스로 총을 겨누는 것을 shift로 바꿔야해서 rotation 관련 변경 필요할 듯..

**Comment by JECH2** [comment]
https://docs.unity3d.com/kr/530/Manual/class-InputManager.html

**Comment by JECH2** [comment]
Player2P update(beta) 완료 & PUSH함!

### 설명
- Player2P는 prefab of player, 
- Key name mapping for Player : Vertical(ad), Horizontal(sw), Fire1(left shift) 
- Key name mapping for Player2P : Vertical_2P(좌우), Horizontal_2P(상하), Fire1_2P(right shift)
- Vertical, Horizontal key name을 바꾸면 에러가 나서, 1P는 뒤에 이름을 따로 붙여주지 않고 진행
- Player2P로 하는 경우 camera following을 하지 않도록 변경(disable)
- 그러나 피격 조건, 게임엔딩 여부 등이 모두 player라는 tag으로 진행 -> player1, 2 구별 불가능 & 둘 중 랜덤하게 하나의 오브젝트가 선택됨 : 추가적인 코드 수정이 필요
- default 모드로 기존에 사용하던 마우스 + wasd  를 이용하여 1P만 조작 가능하게 해둠

###2P 모드 사용방법
- 테스트 하려면 scene view에서 inactive되어 있는 Player2P에 체크하고 Player, Player2P 모두 Player Movement script의 useMouse 체크 해제하고 실행

**Comment by Cliwo** [comment]
![스크린샷 2020-11-15 오후 12 03 46](https://user-images.githubusercontent.com/15336467/99161909-a97c1580-273a-11eb-86b9-829843abe076.png)
![스크린샷 2020-11-15 오후 12 03 52](https://user-images.githubusercontent.com/15336467/99161912-ad0f9c80-273a-11eb-867b-021207f1d6dd.png)
![스크린샷 2020-11-15 오후 12 03 59](https://user-images.githubusercontent.com/15336467/99161913-ada83300-273a-11eb-8ff9-f9dd93a843f8.png)

commit : 2a2ab23
missing component, missing prefab이 발생하고 있습니다.

**Comment by Cliwo** [comment]
![스크린샷 2020-11-15 오후 12 12 33](https://user-images.githubusercontent.com/15336467/99162026-ded53300-273b-11eb-9a72-7b913dd59bd3.png)

대부분의 Scene이 missing material이나 missing component가 발생합니다.
혹시 가능하시다면 유니티를 열기전 Asset폴더 아래에 있는 .meta file을 모두 삭제하시고
유니티로 프로젝트를 열어 주실 수 있으실까요?

그럼 삭제된 .meta file들이 다시 다 생길겁니다.

그 다음에 그상태 그대로 commit 만들어주시고 push 해주실 수 있을까요?

**Comment by JECH2** [comment]
meta 파일 추가 후, git clone 해서 테스트해봤는데 Assets/Scenes/my_Level01 scene은 문제없이 작동합니다!

**Comment by JECH2** [comment]
1P 모드로 할 때 존재하는 Floor는 플레이어의 회전을 마우스로 받는데 필요함. 
기존에 평면으로 존재하던 Floor를 삭제하고 Terrain의 layer를 Floor로 맵핑하면 됩니다.
