### ISSUE TITLE
URP로 업그레이드 

### ISSUE THREAD

**Issue by Cliwo** [JECH2/GameDesignProject_KAIST#48]
Rendering pipeline 교체, material upgrade

**Comment by Cliwo** [comment]
chekced with commit : c9e0a31

**Comment by JECH2** [comment]
새로 산 에셋을 확인해보니, URP로 바꾸려면 에셋들의 shader를 urp용으로 모두 바꾸어야 하는데, 그 과정에서 안고쳐지는 것들이 있어서(ㅠㅠㅠ 어떻게 해야할지 모르겠어요) standard rp로 바꿨습니다!(저희가 이번에 구매한 에셋들이 모두 standard rp로 열었을 때 문제없이 작동하는 것을 확인하였습니다.)
그래서 Rendering pipeline 교체, material downgrade했습니다.

- edit > project settings > scriptable render pipeline settings를 None으로 변경
- 프로젝트 내 모든 material을 Standard shader로 변경

다음의 두 가지 링크를 참고하여 바꿨습니다!
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.1/manual/InstallURPIntoAProject.html
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.1/manual/upgrading-your-shaders.html

see commit 758ff98

**Comment by JECH2** [comment]
see #73
