### ISSUE TITLE
FPS 샘플 대체제 조사 → FPS 자체보다 Multiplay 기능이 들어 있는 샘플을 찾기

### ISSUE THREAD

**Issue by JECH2** [JECH2/GameDesignProject_KAIST#6]

**Comment by byeoli** [comment]
1. Multiplyer-FPS
- 링크 : https://github.com/Armour/Multiplayer-FPS

**Comment by byeoli** [comment]
2. FPS Multiplayer (Unity)
- 링크 : https://github.com/DigitalEpidemic/fps-multiplayer-unity

**Comment by byeoli** [comment]
1번에 대한 Multiply & Character change 로직 document가 괜찮아보임 !
