### ISSUE TITLE
Player Movement in y axis

### ISSUE THREAD

**Issue by JECH2** [JECH2/GameDesignProject_KAIST#61]
현재까지의 플레이어 움직임은 상하(z축), 좌우(x축) 을 움직입니다.
>move(h,v) 시 movement.Set (h, 0f, v);

그 전까지 움직이던 floor는 평평해서 x, z 값만 업데이트되어도 상관없었지만,
새로 사용하게 된 asset의 map은 땅이 울퉁불퉁하여(y값이 변화함), 이 값을 플레이어가 움직였을 때 바꿔주지 않으면 collision에 의해 움직임이 제한됩니다.
즉, 플레이어가 움직일 때 y 값을 땅의 y축에서의 위치를 바탕으로 업데이트하는 것이 필요합니다.

이것만 진행되면 플레이어, 몬스터를 새로운 맵에서 배치하고, 움직이게 하는 것이 가능할 것 같습니다!
> 참고 : https://answers.unity.com/questions/844949/moving-gameobject-along-terrain-based-on-player-mo.html

**Comment by JECH2** [comment]
확인해보니 맵을 구성하는 대부분의 오브젝트(바닥, 나무, 돌 등)에 콜라이더가 붙어있어서 충돌고려는 하지 않아도 될듯 합니다.
그리고 내일 너무 급하면 울퉁불퉁한 언덕 말고, 아래의 이미지처럼 플레이어와 적들을 새로운 맵에서도 평평한 지역에 배치시켜놓고 데모영상 찍으면 될 것 같습니다.
![image](https://user-images.githubusercontent.com/26477914/99574735-1af9e380-2a1b-11eb-9310-62613cfc76a8.png)

**Comment by byeoli** [comment]
hill올라타는거 quaternion.slerp로 구현하는 방법 인것 같음 
[https://answers.unity.com/questions/1401200/i-walk-through-terrainhills.html](url)

**Comment by JECH2** [comment]
기존에 쓰던 rigid body 대신 chracter controller move를 이용하여 언덕을 오를 수 있게 됨. 그러나 맵 자체의 bake 문제로 플레이어가 맵 위에 붕뜨는 현상 관찰.

**Comment by JECH2** [comment]
see #74
