### ISSUE TITLE
No MIC input in MAC OS (Microphone Access Permission Issue)

### ISSUE THREAD

**Issue by JECH2** [JECH2/GameDesignProject_KAIST#68]
** If you are on a Mac running OS 10.14 (or above), it is likely that Unity (and Unity Hub) have not been given microphone access permission

**Comment by byeoli** [comment]
후후,, 이놈의 microphone 문제를 해결하였습니다..

무슨 이유로 된 것인지 사실 잘 모르겠기에.. 제가 한 모든 시도를 적겠습니다 ! 

1. Mac 내 환경설정 세팅 관련
링크 : https://macreports.com/microphone-not-working-in-macos-fix/

2. Mac 내 Microphone 관련 Authorization 
2-1) 링크 : https://docs.unity3d.com/ScriptReference/Application.RequestUserAuthorization.html
-> 이걸로 Log 찍어서 제대로 들어가있나 확인

2-2) 링크 : https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos?language=objc

3. Edit tcc.db
링크 : https://www.reddit.com/r/Ring/comments/ciztw5/ring_macos_app_how_to_make_your_macs_microphone/

4. 위의 것들을 하고. Unity Hub로 들어가서 Unity를 켰더니 -> Mic permission 관련 Pop-up이 나왔음 ! 

5. 새로 산 마이크 & 헤드셋 마이크 둘다 정상적으로 Microphone 사용됨 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
