### ISSUE TITLE
Target Activation 관련 수정사항

### ISSUE THREAD

**Issue by byeoli** [JECH2/GameDesignProject_KAIST#69]
1. 한개의 mapping value를 동시에 가져오니까, 2개의 target이 동시에 활성화 되어버림 !

2. Buffer가 빨리 값이 바뀌지 않아서, target1 활성화 이후에 target2에 바로 가게 되면, 너무 쉽게 이전에 target1에 input으로 들어갔던게 그대로 들어감
- 문제가 안될 수도 있음
- 나중에는 target을 활성화시키는 색이 target마다 바뀔테니까 
[] target 활성화시, mapping value 0으로 되게끔 ! 

3. target activation 하는 과정에서 길게 5초 (예시) 정도 음을 불러야하게끔 수정 !

**Comment by JECH2** [comment]
- target note를 scene view에서 수정 가능(using public variable targetNote)
- 맵 내에 배치된 타겟의 target note를 도. 미, 솔 각각으로 수정
- 50프레임을 돌 때(1~2초?) 연속해서 같은 note가 인지되어야 타겟이 활성화되도록 활성화하는데 걸리는 시간 수정
--> public variable targetActivateCnt 를 통해 수정 가능(난이도 관련)
- target의 material 속성을  transparent로 수정하고 singing 하면서 alpha가 0.8에서 1로 차오르도록 수정
--> 근데 색이 차오르는 것이 안예쁨 ㅠ
see b5f1a88d123d79337a7affa0cba9e1779b8da915

**Comment by JECH2** [comment]
see #75
