### ISSUE TITLE
Windows에서 build해서 multi-play 기능을 test 해보기

### ISSUE THREAD

**Issue by JECH2** [JECH2/GameDesignProject_KAIST#7]

**Comment by Cliwo** [comment]
50% 정도 성공

Test 방법

1. UnityEditor에서 Quick Start 부분을 아래 사진처럼 설정한다.
![1](https://user-images.githubusercontent.com/15336467/94397284-7a1b4480-019e-11eb-9e79-3d558dfaeb4e.png)
S.Alone 부분이 원래 2칸인데 BuildWindow.cs 에서 수정할 수 있다.
Editor에서 서버만 띄우는 방법임.

2. 
![2](https://user-images.githubusercontent.com/15336467/94397364-a46d0200-019e-11eb-9360-a64af6590e40.png)
build 한 exe를 위와 같이 실행한다.
ip 주소만 잘 설정해 주면 다른 machine에서도 충분히 서버로 접속 가능한걸로 보임.


ㅡㅡㅡ 진짜 원격을 테스트하려면 GCP를 빌리거나, 다른 환경이 필요한듯.

**Comment by Cliwo** [comment]
추가적으로 조사한 내용

1. 유동 ip를 사용하는 경우 Ngrok을 이용한 터널링이 필요 (유동 ip를 고정 ip처럼 쓸 수 있게 만들어줌) 다만, 이 방식은 tcp protocol로만 가능한데, 현재 FPS Sample은 udp 프로토콜을 사용함 
    1-1. MarkoPaul0/DatagramTunneler: Simple C++ cross-platform client/server app forwarding UDP datagrams through a TCP connection. - https://github.com/MarkoPaul0/DatagramTunneler 여기에 udp 기반 ngrok이 있는데 사용해 본 적 없음

2. 터널링을 안하려면 aws 나 gcp 같은 머신을 빌려서 고정 ip를 얻고, 서버를 돌릴 수 있게 환경구성이 필요.
    2-1. gcp를 시도해보았으나 무료 크레딧으로는 windows image 기반 머신을 빌릴 수 없고, billing account 설정이 필수. billing account를 설정한다고 바로 돈이 나가는 것은 아니지만, 저번 경험상 의도치않게 유료결제가 된 적이 있어서 주저하고 있음..
그렇다고 linux 로 하자니 linux에서 빌드해 본적이 없으므로 무슨 문제가 생길 지 알 수 없음

**Comment by Cliwo** [comment]
80% 정도 성공
https://drive.google.com/file/d/1lJxZssSk5dl_cZHjtIRo_6Lj557TfSjK/view?usp=sharing

2개의 process로 server에 동시접속 성공
